//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensorDeviceService.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SensorDeviceService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22
        ///25
        ///30
        ///16
        ///33
        ///23
        ///19
        ///19
        ///9
        ///27
        ///22
        ///91
        ///93
        ///43
        ///32
        ///28
        ///82
        ///65
        ///32
        ///26
        ///28
        ///28
        ///24
        ///23
        ///17
        ///19
        ///28
        ///15
        ///22
        ///70
        ///28
        ///26
        ///22
        ///22
        ///12
        ///9
        ///8
        ///12
        ///15
        ///16
        ///24
        ///31
        ///16
        ///19
        ///8
        ///28
        ///20
        ///16
        ///17
        ///10
        ///21
        ///17
        ///39
        ///28
        ///21
        ///10
        ///12
        ///25
        ///15
        ///13
        ///11
        ///11
        ///9
        ///21
        ///21
        ///26
        ///15
        ///8
        ///11
        ///19
        ///31
        ///30
        ///24
        ///69
        ///21
        ///18
        ///23
        ///22
        ///17
        ///22
        ///16
        ///39
        ///19
        ///23
        ///10
        ///14
        ///16
        ///19
        ///25
        ///14
        ///27
        ///25
        ///35
        ///26
        ///33
        ///23
        ///22
        ///20
        ///28
        ///25
        ///23
        ///90
        ///68
        ///74
        ///41
        ///34
        ///34
        ///19
        ///15
        ///13
        ///17
        ///30
        ///25
        ///20
        ///78
        ///26
        ///30
        ///26
        ///18
        ///16
        ///25
        ///22
        ///30
        ///49
        ///33
        ///37
        ///20
        ///27
        ///30
        ///27 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string humidity {
            get {
                return ResourceManager.GetString("humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1007.7
        ///1010.6
        ///1007.6
        ///1017.6
        ///1010.8
        ///1009.2
        ///1009.6
        ///1013.4
        ///1008.9
        ///1007
        ///1011.8
        ///1010.5
        ///994.3
        ///1001.2
        ///1009.7
        ///1013.4
        ///1012.2
        ///1005.8
        ///1009.4
        ///1019.2
        ///1019.3
        ///1013.6
        ///1007.8
        ///1011
        ///1012.9
        ///1010.9
        ///1006.8
        ///1005.2
        ///1004.8
        ///1005.6
        ///1006.1
        ///1004.5
        ///1014.4
        ///1018.7
        ///1015.1
        ///1012.6
        ///1010.9
        ///1007
        ///1011.9
        ///1017.8
        ///1013.4
        ///1009.9
        ///1014.1
        ///1015.7
        ///1011.6
        ///1008.4
        ///1014.1
        ///1019.7
        ///1019.7
        ///1015.8
        ///1010.1
        ///1009.6
        ///1005.3
        ///1007.9
        ///1005.4
        ///1016.5
        ///1017.7
        ///1017.8
        ///1014.9
        ///1015.7
        ///1014.6
        ///1014.2
        ///1012.5
        ///1011.7
        ///1009.2        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pressure {
            get {
                return ResourceManager.GetString("pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.6
        ///0
        ///0
        ///0
        ///1
        ///0.2
        ///0
        ///0
        ///0
        ///1.4
        ///0
        ///2.2
        ///15.6
        ///3.6
        ///0
        ///NA
        ///0
        ///16.8
        ///10.6
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///1.2
        ///0.8
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0.8
        ///0.6
        ///6.4
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0.2
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0.4
        ///0
        ///0
        ///0
        ///3
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0.2
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///1.2
        ///0
        ///5.8
        ///3
        ///11.6
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0.4
        ///1.8
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///8.6
        ///12.6
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///8.4
        ///6.2
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///20
        ///21
        ///3.2
        ///4.8
        ///0
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rainfall {
            get {
                return ResourceManager.GetString("rainfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.8
        ///24.3
        ///23.2
        ///26.5
        ///29.7
        ///28.9
        ///24.6
        ///25.5
        ///30.2
        ///28.2
        ///28.8
        ///17
        ///15.8
        ///19.8
        ///23.5
        ///26.2
        ///18.1
        ///21.5
        ///21
        ///23.2
        ///27.3
        ///31.6
        ///30.8
        ///29
        ///31.2
        ///33
        ///31.2
        ///32.1
        ///26.1
        ///18.2
        ///22.7
        ///25.7
        ///22.1
        ///26.5
        ///33.9
        ///34.4
        ///36.8
        ///38.4
        ///27.6
        ///26.6
        ///29.3
        ///30
        ///33.2
        ///35.7
        ///41.5
        ///27.1
        ///25.5
        ///25.8
        ///30.5
        ///34.4
        ///37.7
        ///36.1
        ///33.1
        ///33
        ///29.7
        ///32.1
        ///36.5
        ///36.2
        ///39.2
        ///40.1
        ///41.2
        ///42
        ///41.9
        ///37.1
        ///36.2
        ///35.2
        ///39.7
        ///41.6
        ///43.4
        ///38.5
        ///29.4
        ///25.8
        ///24.9
        ///17.3
        ///27.6
        ///28.5
        ///29.2
        ///29.5
        ///27
        ///30.7
        ///32.7
        ///26.8
        ///29.8
        ///31.3
        ///33.4
        ///28.6
        ///29.3
        ///30.5
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string temperature {
            get {
                return ResourceManager.GetString("temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24
        ///22
        ///26
        ///9
        ///20
        ///24
        ///24
        ///17
        ///28
        ///11
        ///6
        ///13
        ///28
        ///20
        ///30
        ///22
        ///9
        ///20
        ///17
        ///6
        ///9
        ///22
        ///20
        ///13
        ///19
        ///13
        ///26
        ///30
        ///30
        ///22
        ///17
        ///31
        ///11
        ///7
        ///17
        ///26
        ///26
        ///30
        ///24
        ///9
        ///11
        ///17
        ///15
        ///17
        ///17
        ///28
        ///31
        ///11
        ///15
        ///15
        ///20
        ///17
        ///48
        ///28
        ///28
        ///13
        ///7
        ///17
        ///13
        ///11
        ///11
        ///4
        ///9
        ///7
        ///9
        ///11
        ///19
        ///15
        ///33
        ///22
        ///11
        ///13
        ///11
        ///15
        ///24
        ///0
        ///15
        ///11
        ///11
        ///13
        ///22
        ///17
        ///9
        ///15
        ///22
        ///24
        ///17
        ///2
        ///6
        ///NA
        ///13
        ///9
        ///26
        ///33
        ///33
        ///13
        ///20
        ///11
        ///17
        ///4
        ///19
        ///9
        ///13
        ///22
        ///17
        ///20
        ///17
        ///11
        ///7
        ///7
        ///11
        ///19
        ///24
        ///20
        ///9
        ///20
        ///11
        ///17
        ///6
        ///9
        ///13
        ///6
        ///11
        ///17
        ///13
        ///19
        ///19
        ///7
        ///13
        ///13
        ///11
        ///11
        ///6
        ///7
        ///15
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string windspeed {
            get {
                return ResourceManager.GetString("windspeed", resourceCulture);
            }
        }
    }
}
